### ISSUE TITLE
Would you like to support models from the Qwen 2.5 series?

### ISSUE THREAD

**Issue by ArcherShirou** [TransformerLensOrg/TransformerLens#771] opened 2024-11-05 09:14 UTC
The Qwen 2.5 series models are commonly used in open-source models, offering good performance and an appropriate size. However, I noticed that the current version doesn't support Qwen 2.5. May I ask if there are any plans to support it in the future?

**Comment by bryce13950** [comment] 2024-11-12 22:26
Duplicate of #762. This is the second time it has been asked for. We can fast track it to make sure it gets added to the next release.

**Closed by bryce13950** 2024-11-12 22:26 UTC
